// crates/mach-desktop/ui/src/views/ChordOverlay.tsx
// Chord prefix overlay — shows the available continuations after a chord
// key is held (g → i:inbox, s:starred, …). Slides up from bottom-right.
import { Show, For } from "solid-js";

export default function ChordOverlay(props: {
  show: boolean;
  buf: string;
  conts: { next: string; action_name: string }[];
}) {
  return (
    <Show when={props.show}>
      <div
        class="absolute bottom-12 right-6 rounded-[12px] p-4 min-w-[280px] z-40 glass"
        style={{ "box-shadow": "var(--shadow-pop)" }}
      >
        <div class="text-[11px] uppercase tracking-wider text-fg-mute mb-3">
          Prefix <span class="kbd">{props.buf}</span>
        </div>
        <ul class="flex flex-col gap-1.5">
          <For each={props.conts}>
            {(c) => (
              <li class="flex items-center gap-3 text-[13px]">
                <span class="kbd">{c.next}</span>
                <span class="text-fg-soft">{c.action_name.replace(/_/g, " ")}</span>
              </li>
            )}
          </For>
        </ul>
      </div>
    </Show>
  );
}

// crates/mach-desktop/ui/src/views/ChordOverlay.svelte
<script lang="ts">
  let { show, buf, conts }: { show: boolean; buf: string; conts: { next: string; action_name: string }[] } = $props();
</script>

{#if show}
  <div class="overlay">
    <div class="prefix">Prefix <kbd>{buf}</kbd></div>
    <ul>
      {#each conts as continuation}
        <li><kbd>{continuation.next}</kbd><span>{continuation.action_name.replace(/_/g, " ")}</span></li>
      {/each}
    </ul>
  </div>
{/if}

<style>
  .overlay { position: absolute; bottom: 18px; left: 50%; z-index: 40; min-width: 280px; padding: 16px; transform: translateX(-50%); border: 1px solid var(--border); border-radius: 12px; background: var(--surface); box-shadow: 0 12px 36px color-mix(in oklab, black 30%, transparent); }
  .prefix { margin-bottom: 12px; color: var(--muted); font-size: 11px; letter-spacing: .08em; text-transform: uppercase; }
  ul { display: flex; flex-direction: column; gap: 6px; margin: 0; padding: 0; list-style: none; }
  li { display: flex; align-items: center; gap: 12px; color: var(--muted); font-size: 13px; }
  kbd { padding: 2px 5px; border: 1px solid var(--border); border-radius: 4px; background: var(--surface-2); color: var(--accent); font-family: var(--font-mono); font-size: 11px; text-transform: none; }
</style>
