// crates/mach-desktop/ui/src/views/Composer.tsx
// Compose modal — backdrop blur, generous spacing, no field borders
// except a subtle bottom rule that focuses the eye on the body editor.
import { createSignal, onMount } from "solid-js";
import { Send } from "../lib/Icon";

export default function Composer(props: { onClose: () => void }) {
  const [to, setTo] = createSignal("");
  const [cc, setCc] = createSignal("");
  const [subject, setSubject] = createSignal("");
  const [body, setBody] = createSignal("");
  let firstInput: HTMLInputElement | undefined;
  onMount(() => firstInput?.focus());

  return (
    <div
      class="absolute inset-0 z-30 flex items-start justify-center pt-24 px-4"
      style={{
        background: "color-mix(in oklab, var(--color-bg) 60%, transparent)",
        "backdrop-filter": "blur(8px)",
      }}
      onClick={(e) => {
        if (e.currentTarget === e.target) props.onClose();
      }}
    >
      <div
        class="rounded-[16px] w-[680px] max-w-[92vw] overflow-hidden glass"
        style={{ "box-shadow": "var(--shadow-pop)" }}
      >
        <header class="px-6 pt-5 pb-4 flex items-center justify-between border-b border-fg-dim/15">
          <h2 class="text-[15px] font-semibold tracking-tight">New message</h2>
          <button
            class="text-fg-mute hover:text-fg text-[12px]"
            onClick={props.onClose}
          >
            esc
          </button>
        </header>

        <div class="px-6">
          <Field label="To" value={to()} onInput={setTo} ref_={(r) => (firstInput = r)} />
          <Field label="Cc" value={cc()} onInput={setCc} />
          <Field label="Subject" value={subject()} onInput={setSubject} />
        </div>

        <textarea
          class="w-full bg-transparent px-6 py-4 text-[14px] leading-relaxed h-56 outline-none resize-none placeholder:text-fg-mute"
          placeholder="Write your message…"
          value={body()}
          onInput={(e) => setBody(e.currentTarget.value)}
        />

        <footer class="px-6 py-3 border-t border-fg-dim/15 flex items-center justify-between text-[11.5px] text-fg-mute">
          <div class="flex items-center gap-3">
            <span class="kbd">⌘↵</span> send · <span class="kbd">⌘S</span> save · <span class="kbd">esc</span> close
          </div>
          <button
            class="flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent/15 text-accent hover:bg-accent/25 transition-colors text-[12.5px] font-medium"
            onClick={() => {
              /* placeholder — send wiring lives in the outbox + send-later loop */
            }}
            disabled
            title="send wiring lands with sync engine (see tasks/todo.md)"
          >
            <Send size={13} />
            Send
          </button>
        </footer>
      </div>
    </div>
  );
}

function Field(props: {
  label: string;
  value: string;
  onInput: (s: string) => void;
  ref_?: (el: HTMLInputElement) => void;
}) {
  return (
    <div class="flex items-center gap-4 border-b border-fg-dim/10 py-3">
      <label class="w-16 text-fg-mute text-[12px] uppercase tracking-wider">
        {props.label}
      </label>
      <input
        ref={props.ref_}
        class="flex-1 bg-transparent text-[14px] outline-none placeholder:text-fg-mute"
        value={props.value}
        onInput={(e) => props.onInput(e.currentTarget.value)}
      />
    </div>
  );
}

// crates/mach-desktop/ui/src/views/Composer.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Icon from "../lib/Icon.svelte";

  let { onClose }: { onClose: () => void } = $props();
  let to = $state("");
  let cc = $state("");
  let subject = $state("");
  let body = $state("");
  let firstInput: HTMLInputElement;

  onMount(() => firstInput?.focus());
</script>

<div class="backdrop" role="presentation" onclick={(event) => event.currentTarget === event.target && onClose()}>
  <div class="modal" role="dialog" aria-modal="true" aria-labelledby="composer-title">
    <header>
      <h2 id="composer-title">New message</h2>
      <button class="escape" onclick={onClose}>esc</button>
    </header>
    <div class="fields">
      <label><span>To</span><input bind:this={firstInput} bind:value={to} /></label>
      <label><span>Cc</span><input bind:value={cc} /></label>
      <label><span>Subject</span><input bind:value={subject} /></label>
    </div>
    <textarea bind:value={body} placeholder="Write your message…"></textarea>
    <footer>
      <div><kbd>⌘↵</kbd> send · <kbd>⌘S</kbd> save · <kbd>esc</kbd> close</div>
      <button class="send" disabled title="send wiring lands with sync engine (see tasks/todo.md)">
        <Icon name="send" size={13} /> Send
      </button>
    </footer>
  </div>
</div>

<style>
  .backdrop { position: absolute; inset: 0; z-index: 30; display: flex; align-items: flex-start; justify-content: center; padding: 96px 16px 16px; background: color-mix(in oklab, var(--bg) 60%, transparent); backdrop-filter: blur(8px); }
  .modal { width: 680px; max-width: 92vw; overflow: hidden; border-radius: 16px; background: var(--surface); box-shadow: 0 20px 64px color-mix(in oklab, black 35%, transparent); }
  header { display: flex; align-items: center; justify-content: space-between; padding: 20px 24px 16px; border-bottom: 1px solid var(--border); }
  h2 { margin: 0; font-size: 15px; font-weight: 600; letter-spacing: -.01em; }
  .escape { border: 0; background: transparent; color: var(--muted); font-size: 12px; }
  .escape:hover { color: var(--text); }
  .fields { padding: 0 24px; }
  label { display: flex; align-items: center; gap: 16px; padding: 12px 0; border-bottom: 1px solid var(--border); }
  label span { width: 64px; color: var(--muted); font-size: 12px; letter-spacing: .08em; text-transform: uppercase; }
  input, textarea { border: 0; background: transparent; color: var(--text); font-family: inherit; outline: 0; }
  input { min-width: 0; flex: 1; font-size: 14px; }
  textarea { width: 100%; height: 14rem; padding: 16px 24px; resize: none; font-size: 14px; line-height: 1.6; }
  textarea::placeholder { color: var(--muted); }
  footer { display: flex; align-items: center; justify-content: space-between; padding: 12px 24px; border-top: 1px solid var(--border); color: var(--muted); font-size: 11.5px; }
  kbd { padding: 2px 5px; border: 1px solid var(--border); border-radius: 4px; background: var(--surface-2); font-family: var(--font-mono); font-size: 11px; }
  .send { display: inline-flex; align-items: center; gap: 8px; padding: 6px 12px; border: 0; border-radius: 999px; background: color-mix(in oklab, var(--accent) 15%, transparent); color: var(--accent); font-size: 12.5px; font-weight: 500; }
  .send:disabled { cursor: default; opacity: .68; }
</style>
