// crates/mach-desktop/ui/src/views/Inbox.svelte
<script lang="ts">
  import type { ThreadSummary } from "../lib/ipc";
  import { avatarColor, initialsFor } from "../lib/avatar";
  import Icon from "../lib/Icon.svelte";

  const ROW_H = 64;

  let {
    v,
    onSelect,
    onOpen,
  }: {
    v: { kind: "inbox"; label: string; threads: ThreadSummary[]; selected: number };
    onSelect: (index: number) => void;
    onOpen: (index: number) => void;
  } = $props();

  let highlight = $state<HTMLDivElement>();
  let scroller = $state<HTMLDivElement>();

  $effect(() => {
    const index = v.selected;
    if (!highlight) return;
    highlight.style.transform = `translateY(${index * ROW_H}px)`;
    if (!scroller) return;
    const top = index * ROW_H;
    const bottom = top + ROW_H;
    const viewTop = scroller.scrollTop;
    const viewBottom = viewTop + scroller.clientHeight;
    if (top < viewTop) scroller.scrollTo({ top, behavior: "instant" as ScrollBehavior });
    else if (bottom > viewBottom) {
      scroller.scrollTo({ top: bottom - scroller.clientHeight, behavior: "instant" as ScrollBehavior });
    }
  });

  function prettySender(raw: string): string {
    const match = raw.match(/^\s*"?([^"<]+?)"?\s*<.+>$/);
    if (match) return match[1].trim();
    const email = raw.match(/^([\w.+-]+)@([\w.-]+)$/);
    if (email) return email[2];
    return raw;
  }

  function prettyDate(iso: string): string {
    const date = new Date(iso);
    const diff = Date.now() - date.getTime();
    const minute = 60 * 1000;
    const hour = 60 * minute;
    const day = 24 * hour;
    if (diff < day) return date.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
    if (diff < 7 * day) return date.toLocaleDateString([], { weekday: "short" });
    if (diff < 365 * day) return date.toLocaleDateString([], { month: "short", day: "numeric" });
    return date.toLocaleDateString([], { year: "numeric" });
  }
</script>

<div bind:this={scroller} class="list" role="list">
  {#if v.threads.length === 0}
    <div class="empty"><span>Inbox zero</span><small>Nothing in this view.</small></div>
  {:else}
    <div bind:this={highlight} class="highlight" style:height={`${ROW_H}px`}></div>
    {#each v.threads as thread, index (thread.id)}
      <button
        type="button"
        class:selected={index === v.selected}
        class="row"
        style:height={`${ROW_H}px`}
        onclick={() => onSelect(index)}
        ondblclick={() => onOpen(index)}
      >
        <div class="indicators">
          {#if thread.unread}<span class="unread" aria-label="unread"></span>{:else}<span class="spacer"></span>{/if}
          {#if thread.starred}<Icon name="star" size={10} class="star" ariaLabel="starred" />{/if}
        </div>
        <span class="avatar" style:background={avatarColor(thread.participants[0] ?? "(no sender)")} aria-hidden="true">
          {initialsFor(thread.participants[0] ?? "(no sender)")}
        </span>
        <div class="content">
          <div class="line">
            <span class="account">{thread.account_id}</span>
            <span class:unread-text={thread.unread} class="sender">{prettySender(thread.participants[0] ?? "(no sender)")}</span>
            <span class="summary">
              <span class:unread-text={thread.unread}>{thread.subject || "(no subject)"}</span>
              <span class="snippet"> — {thread.snippet}</span>
            </span>
          </div>
        </div>
        <div class:unread-date={thread.unread} class="date">{prettyDate(thread.last_message_at)}</div>
      </button>
    {/each}
  {/if}
</div>

<style>
  .list { position: relative; height: 100%; overflow-y: auto; }
  .empty { display: flex; height: 100%; flex-direction: column; align-items: center; justify-content: center; gap: 8px; color: var(--muted); user-select: none; }
  .empty span { font-size: 20px; }
  .empty small { font-size: 14px; }
  .highlight { position: absolute; top: 0; right: 0; left: 0; pointer-events: none; background: color-mix(in oklab, var(--accent) 12%, transparent); border-left: 2px solid var(--accent); transition: transform 90ms cubic-bezier(.22,1,.36,1); will-change: transform; }
  .row { position: relative; display: flex; width: 100%; align-items: center; gap: 12px; padding: 0 20px; border: 0; background: transparent; color: inherit; text-align: left; cursor: pointer; user-select: none; transition: background 150ms; }
  .row:not(.selected):hover { background: var(--hover); }
  .indicators { display: flex; width: 12px; flex-shrink: 0; flex-direction: column; align-items: center; gap: 4px; }
  .unread, .spacer { width: 8px; height: 8px; }
  .unread { border-radius: 50%; background: var(--accent); }
  :global(.star) { color: var(--starred); }
  .avatar { display: inline-flex; width: 32px; height: 32px; flex-shrink: 0; align-items: center; justify-content: center; border-radius: 50%; color: white; font-size: 12px; font-weight: 600; letter-spacing: .02em; }
  .content { min-width: 0; flex: 1; }
  .line { display: flex; min-width: 0; align-items: baseline; gap: 8px; }
  .account { flex-shrink: 0; padding: 2px 6px; border-radius: 4px; background: var(--surface-2); color: var(--muted); font-size: 10px; }
  .sender { max-width: 30%; flex-shrink: 0; overflow: hidden; color: var(--muted); font-size: 14px; font-weight: 500; text-overflow: ellipsis; white-space: nowrap; }
  .summary { min-width: 0; overflow: hidden; color: var(--text); text-overflow: ellipsis; white-space: nowrap; }
  .snippet { color: var(--muted); }
  .unread-text { color: var(--text); font-weight: 600; }
  .date { flex-shrink: 0; color: var(--muted); font-size: 12px; font-variant-numeric: tabular-nums; text-align: right; }
  .unread-date { color: var(--text); }
</style>

// crates/mach-desktop/ui/src/views/Inbox.tsx
// Inbox list with refined typography + sender avatars. Single-row layout
// with hierarchy: avatar · sender · subject + snippet · time.
import { createMemo, For, Show, createEffect } from "solid-js";
import type { ThreadSummary } from "../lib/ipc";
import { avatarColor, initialsFor } from "../lib/avatar";
import { Star } from "../lib/Icon";

const ROW_H = 64;

export default function Inbox(props: {
  v: {
    kind: "inbox";
    label: string;
    threads: ThreadSummary[];
    selected: number;
  };
  onSelect: (i: number) => void;
  onOpen: (i: number) => void;
}) {
  let highlight: HTMLDivElement | undefined;
  let scroller: HTMLDivElement | undefined;

  // Selection moves via CSS transform — GPU-composited, no animation queue
  // when holding j/k. Also auto-scroll the selected row into view.
  createEffect(() => {
    const i = props.v.selected;
    if (!highlight) return;
    highlight.style.transform = `translateY(${i * ROW_H}px)`;

    if (!scroller) return;
    const top = i * ROW_H;
    const bottom = top + ROW_H;
    const viewTop = scroller.scrollTop;
    const viewBottom = viewTop + scroller.clientHeight;
    if (top < viewTop) scroller.scrollTo({ top, behavior: "instant" as ScrollBehavior });
    else if (bottom > viewBottom)
      scroller.scrollTo({ top: bottom - scroller.clientHeight, behavior: "instant" as ScrollBehavior });
  });

  const list = createMemo(() => props.v.threads);

  return (
    <div
      ref={scroller}
      class="relative h-full overflow-y-auto"
      role="list"
    >
      <Show when={list().length === 0}>
        <div class="flex flex-col items-center justify-center h-full text-fg-mute select-none gap-2">
          <span class="text-xl">Inbox zero</span>
          <span class="text-sm">Nothing in this view.</span>
        </div>
      </Show>
      <div
        ref={highlight}
        class="absolute left-0 right-0 row-selected pointer-events-none"
        style={{
          height: `${ROW_H}px`,
          top: 0,
          transition: "transform 90ms cubic-bezier(0.22, 1, 0.36, 1)",
          "will-change": "transform",
        }}
      />
      <For each={list()}>
        {(t, i) => (
          <Row
            t={t}
            selected={i() === props.v.selected}
            onClick={() => props.onSelect(i())}
            onDoubleClick={() => props.onOpen(i())}
          />
        )}
      </For>
    </div>
  );
}

function Row(props: {
  t: ThreadSummary;
  selected: boolean;
  onClick: () => void;
  onDoubleClick: () => void;
}) {
  const senderRaw = createMemo(() => props.t.participants[0] ?? "(no sender)");
  const senderName = createMemo(() => prettySender(senderRaw()));
  const initials = createMemo(() => initialsFor(senderRaw()));
  const avatarBg = createMemo(() => avatarColor(senderRaw()));
  const when = createMemo(() => prettyDate(props.t.last_message_at));

  return (
    <div
      class={`
        relative flex items-center gap-3 px-5 cursor-pointer select-none
        transition-colors duration-150
        ${props.selected ? "" : "hover:bg-bg-elev-3/40"}
      `}
      style={{ height: `${ROW_H}px` }}
      onClick={props.onClick}
      onDblClick={props.onDoubleClick}
      role="listitem"
    >
      {/* Unread + star indicator column */}
      <div class="flex flex-col items-center gap-1 w-3 shrink-0">
        <Show
          when={props.t.unread}
          fallback={<span class="w-2 h-2" aria-hidden />}
        >
          <span class="unread-dot w-2 h-2" aria-label="unread" />
        </Show>
        <Show when={props.t.starred}>
          <Star size={10} class="text-starred" aria-label="starred" />
        </Show>
      </div>

      {/* Avatar */}
      <span
        class="avatar"
        style={{ background: avatarBg() }}
        aria-hidden
      >
        {initials()}
      </span>

      {/* Sender + subject + snippet */}
      <div class="flex-1 min-w-0">
        <div class="flex items-baseline gap-2">
          <span class="shrink-0 rounded bg-bg-elev-3 px-1.5 py-0.5 text-[10px] text-fg-mute">
            {props.t.account_id}
          </span>
          <span
            class={`truncate text-sm ${
              props.t.unread ? "text-fg font-semibold" : "text-fg-soft font-medium"
            }`}
            style={{ "max-width": "30%" }}
          >
            {senderName()}
          </span>
          <span class={`truncate ${props.t.unread ? "text-fg" : "text-fg-soft"}`}>
            <span class={props.t.unread ? "font-semibold" : "font-normal"}>
              {props.t.subject || "(no subject)"}
            </span>
            <span class="text-fg-mute"> — {props.t.snippet}</span>
          </span>
        </div>
      </div>

      {/* Date */}
      <div class={`shrink-0 text-xs tabular-nums ${props.t.unread ? "text-fg-soft" : "text-fg-mute"}`}>
        {when()}
      </div>
    </div>
  );
}

/**
 * Strip a quoted "Display Name" out of a `Name <email>` and bias toward
 * the email's @domain when no name is present.
 */
function prettySender(raw: string): string {
  const m = raw.match(/^\s*"?([^"<]+?)"?\s*<.+>$/);
  if (m) return m[1].trim();
  const e = raw.match(/^([\w.+-]+)@([\w.-]+)$/);
  if (e) return e[2]; // domain — feels more recognizable than the local part
  return raw;
}

function prettyDate(iso: string): string {
  const d = new Date(iso);
  const now = Date.now();
  const diff = now - d.getTime();
  const min = 60 * 1000;
  const hr = 60 * min;
  const day = 24 * hr;
  if (diff < day) return d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
  if (diff < 7 * day) return d.toLocaleDateString([], { weekday: "short" });
  if (diff < 365 * day) return d.toLocaleDateString([], { month: "short", day: "numeric" });
  return d.toLocaleDateString([], { year: "numeric" });
}
