// crates/mach-desktop/ui/src/views/Search.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { ThreadSummary } from "../lib/ipc";
  import { avatarColor, initialsFor } from "../lib/avatar";
  import Icon from "../lib/Icon.svelte";

  let {
    v,
    onInput,
    onEnter,
    onEsc,
    onMove,
  }: {
    v: { kind: "search"; query: string; results: ThreadSummary[]; selected: number; background: unknown };
    onInput: (query: string) => void;
    onEnter: () => void;
    onEsc: () => void;
    onMove: (delta: number) => void;
  } = $props();

  let input: HTMLInputElement;
  let timer: number | undefined;
  onMount(() => {
    input?.focus();
    return () => timer !== undefined && window.clearTimeout(timer);
  });

  function debouncedInput(query: string) {
    if (timer !== undefined) window.clearTimeout(timer);
    timer = window.setTimeout(() => onInput(query), 80);
  }
</script>

<div class="overlay">
  <div class="searchbar">
    <Icon name="search" size={18} class="search-icon" />
    <input
      bind:this={input}
      value={v.query}
      placeholder="Search subjects, senders, body…"
      oninput={(event) => debouncedInput(event.currentTarget.value)}
      onkeydown={(event) => {
        if (event.key === "Escape") { event.preventDefault(); onEsc(); }
        else if (event.key === "Enter") { event.preventDefault(); onEnter(); }
        else if (event.key === "ArrowDown") { event.preventDefault(); onMove(1); }
        else if (event.key === "ArrowUp") { event.preventDefault(); onMove(-1); }
      }}
    />
    <span class="count">{v.results.length}</span>
  </div>
  <div class="results">
    {#each v.results as thread, index (thread.id)}
      {@const sender = thread.participants[0] ?? "(no sender)"}
      <div class:selected={index === v.selected} class="result">
        <span class="avatar" style:background={avatarColor(sender)} aria-hidden="true">{initialsFor(sender)}</span>
        <div>
          <p class="account">{thread.account_id}</p>
          <p class="subject">{thread.subject}</p>
          <p class="snippet">{sender} — {thread.snippet}</p>
        </div>
      </div>
    {/each}
  </div>
</div>

<style>
  .overlay { position: absolute; inset: 0; z-index: 20; display: flex; flex-direction: column; background: color-mix(in oklab, var(--bg) 80%, transparent); backdrop-filter: blur(12px); }
  .searchbar { display: flex; align-items: center; gap: 12px; padding: 20px 24px; border-bottom: 1px solid var(--border); }
  :global(.search-icon) { flex-shrink: 0; color: var(--muted); }
  input { min-width: 0; flex: 1; border: 0; background: transparent; color: var(--text); font-size: 15px; outline: 0; }
  input::placeholder { color: var(--muted); }
  .count { color: var(--muted); font-size: 11.5px; font-variant-numeric: tabular-nums; }
  .results { flex: 1; overflow-y: auto; }
  .result { display: flex; align-items: center; gap: 12px; padding: 12px 24px; cursor: pointer; transition: background 150ms; }
  .result:not(.selected):hover { background: var(--hover); }
  .result.selected { background: color-mix(in oklab, var(--accent) 15%, transparent); }
  .avatar { display: inline-flex; width: 32px; height: 32px; flex-shrink: 0; align-items: center; justify-content: center; border-radius: 50%; color: white; font-size: 12px; font-weight: 600; }
  .result > div { min-width: 0; flex: 1; }
  p { overflow: hidden; margin: 0; text-overflow: ellipsis; white-space: nowrap; }
  .account { color: var(--muted); font-size: 10px; }
  .subject { color: var(--text); font-size: 13.5px; font-weight: 500; }
  .snippet { color: var(--muted); font-size: 12px; }
</style>

// crates/mach-desktop/ui/src/views/Search.tsx
// Search overlay. Big input at top, results list below, debounced filter.
import { For, onMount, createMemo } from "solid-js";
import type { ThreadSummary } from "../lib/ipc";
import { avatarColor, initialsFor } from "../lib/avatar";
import { Search as SearchIcon } from "../lib/Icon";

export default function SearchOverlay(props: {
  v: {
    kind: "search";
    query: string;
    results: ThreadSummary[];
    selected: number;
    background: unknown;
  };
  onInput: (q: string) => void;
  onEnter: () => void;
  onEsc: () => void;
  onMove: (d: number) => void;
}) {
  let input: HTMLInputElement | undefined;
  onMount(() => input?.focus());

  let timer: number | undefined;
  function debouncedInput(q: string) {
    if (timer) window.clearTimeout(timer);
    timer = window.setTimeout(() => props.onInput(q), 80);
  }

  return (
    <div
      class="absolute inset-0 z-20 flex flex-col"
      style={{
        background: "color-mix(in oklab, var(--color-bg) 80%, transparent)",
        "backdrop-filter": "blur(12px)",
      }}
    >
      <div class="border-b border-fg-dim/10 px-6 py-5 flex items-center gap-3">
        <SearchIcon size={18} class="text-fg-mute" />
        <input
          ref={input}
          class="flex-1 bg-transparent outline-none text-fg text-[15px] placeholder:text-fg-mute"
          placeholder="Search subjects, senders, body…"
          value={props.v.query}
          onInput={(e) => debouncedInput(e.currentTarget.value)}
          onKeyDown={(e) => {
            if (e.key === "Escape") {
              e.preventDefault();
              props.onEsc();
            } else if (e.key === "Enter") {
              e.preventDefault();
              props.onEnter();
            } else if (e.key === "ArrowDown") {
              e.preventDefault();
              props.onMove(1);
            } else if (e.key === "ArrowUp") {
              e.preventDefault();
              props.onMove(-1);
            }
          }}
        />
        <span class="text-[11.5px] text-fg-mute tabular-nums">
          {props.v.results.length || 0}
        </span>
      </div>
      <div class="flex-1 overflow-y-auto">
        <For each={props.v.results}>
          {(t, i) => <SearchRow t={t} selected={i() === props.v.selected} />}
        </For>
      </div>
    </div>
  );
}

function SearchRow(props: { t: ThreadSummary; selected: boolean }) {
  const senderRaw = createMemo(() => props.t.participants[0] ?? "(no sender)");
  const initials = createMemo(() => initialsFor(senderRaw()));
  const avatarBg = createMemo(() => avatarColor(senderRaw()));
  return (
    <div
      class={`flex items-center gap-3 px-6 py-3 cursor-pointer transition-colors ${
        props.selected ? "bg-accent/15" : "hover:bg-bg-elev-3/40"
      }`}
    >
      <span class="avatar" style={{ background: avatarBg() }} aria-hidden>
        {initials()}
      </span>
      <div class="flex-1 min-w-0">
        <p class="text-fg-mute text-[10px] truncate">
          {props.t.account_id}
        </p>
        <p class="text-fg text-[13.5px] font-medium truncate">
          {props.t.subject}
        </p>
        <p class="text-fg-mute text-[12px] truncate">
          {senderRaw()} — {props.t.snippet}
        </p>
      </div>
    </div>
  );
}
